# Generated by Django 2.1.4 on 2020-03-13 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('comment_user', models.CharField(max_length=50, verbose_name='评论用户')),
                ('comment_content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('comment_score', models.FloatField(max_length=50, verbose_name='情感评分')),
                ('filmname', models.CharField(default=True, max_length=50, verbose_name='电影名')),
            ],
            options={
                'verbose_name': '电影分析过程',
                'verbose_name_plural': '电影分析过程',
            },
        ),
    ]
