# Generated by Django 2.1.4 on 2020-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=20, verbose_name='电影名')),
                ('scrapy_totle', models.IntegerField(default=0, verbose_name='爬取的总条数')),
                ('mean', models.FloatField(blank=True, default=0, verbose_name='平均数')),
                ('pos', models.CharField(max_length=200, verbose_name='正向主题')),
                ('neg', models.CharField(max_length=200, verbose_name='负向主题')),
            ],
            options={
                'verbose_name': '电影详情，及分析结果',
                'verbose_name_plural': '电影详情，及分析结果',
            },
        ),
    ]
