# Generated by Django 2.1.4 on 2020-03-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='neg',
            field=models.TextField(verbose_name='负向主题'),
        ),
        migrations.AlterField(
            model_name='film',
            name='pos',
            field=models.TextField(verbose_name='正向主题'),
        ),
    ]
