# Generated by Django 2.1.4 on 2020-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getinfo', '0002_auto_20200313_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='types',
            field=models.CharField(blank=True, max_length=200, verbose_name='电影类型'),
        ),
    ]
